### ISSUE TITLE
fyi: ruby-wavefile now packaged for Debian

### ISSUE THREAD

**Issue by hzulla** [jstrait/wavefile#17]
Hi,

just fyi: the wavefile gem is being used by Sonic Pi to teach coding to kids. In an effort to bring Sonic Pi to Debian, the wavefile gem has now been packaged: [ruby-wavefile at Debian](https://packages.debian.org/sid/ruby-wavefile).

Thanks for making this gem.

**Comment by jstrait** [comment]
No problem, thanks for the info!
