### ISSUE TITLE
Duration does not override equality

### ISSUE THREAD

**Issue by chrylis** [jstrait/wavefile#23]
Two Durations that specify the exact same duration do not evaluate as equal.

**Comment by jstrait** [comment]
Thanks for the heads up! It makes sense that two durations constructed from the same sample frame count and sample rate should be regarded as equal.

Out of curiosity, has this caused an issue for you in a particular use case?

**Comment by jstrait** [comment]
This is now fixed in v0.8.0, which was released today, so closing this issue. Thanks for suggesting this improvement!
