### ISSUE TITLE
How i can play file

### ISSUE THREAD

**Issue by arbims** [jstrait/wavefile#38]
I Want play file

**Comment by jstrait** [comment]
Hi @arbims, sorry for taking awhile to respond. This gem doesn't have the ability to play *.wav files. It will let you read and write the raw data in a *.wav file, but to play a file you'll need to use something else. If you are wanting to play files using Ruby, I am not sure of the best way to do that. It seems like the [Gosu](https://github.com/gosu/gosu) gem might let you play *.wav files using Ruby, but I haven't used it before. Hope this helps!
